services:
  # Backend API Service
  - type: web
    name: starknet-founders-bot-backend
    env: python
    runtime: python
    rootDir: backend
    region: frankfurt
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:socket_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://starknet-founders-bot-frontend-zc93.onrender.com
      - key: PRODUCTION_FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.11"
    healthCheckPath: /

  # Frontend Web Service
  - type: web
    name: starknet-founders-bot-frontend
    env: node
    runtime: node
    rootDir: frontend
    region: frankfurt
    plan: starter
    buildCommand: bun install && bun run build
    startCommand: bun start
    envVars:
      # SUPABASE AUTH VARIABLES:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      
      # KEEP API configuration:
      - key: NEXT_PUBLIC_API_URL
        value: https://starknet-founders-bot-backend-zc93.onrender.com
      - key: NODE_VERSION
        value: "20"
    healthCheckPath: /
    autoDeploy: true 