services:
  # Backend API Service
  - type: web
    name: starknet-founders-bot-backend
    env: python  # Explicit env helps with validation
    runtime: python
    rootDir: backend
    region: frankfurt
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FRONTEND_URL
        fromService:
          type: web
          name: starknet-founders-bot-frontend
          property: HOST_URL
      - key: PRODUCTION_FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /
    disks:  # Correctly nested with proper indentation
      - name: chroma-data
        mountPath: /chroma_db
        sizeGB: 1  # Explicit size is required; adjust as needed (billed ~$0.25/GB/month)

  # Frontend Web Service
  - type: web
    name: starknet-founders-bot-frontend
    env: node  # Explicit env for Node
    runtime: node
    rootDir: frontend
    region: frankfurt
    plan: starter
    preBuildCommand: npm install -g bun  # Correct field name; installs Bun before build
    buildCommand: bun install && bun run build
    startCommand: bun start
    envVars:
      - key: GITHUB_ID
        sync: false
      - key: GITHUB_SECRET
        sync: false
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: starknet-founders-bot-frontend
          property: HOST_URL
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: starknet-founders-bot-backend
          property: HOST_URL
      - key: NODE_VERSION
        value: 20
    healthCheckPath: /
    autoDeploy: true 