services:
  # Backend API Service
  - type: web
    name: starknet-founders-bot-backend
    runtime: python
    repo: https://github.com/omarespejel/roastmypitch  # Optional: Your repo URL
    rootDir: backend  # Better for monorepo: Set root to backend folder
    region: frankfurt  # For EU latency (Berlin)
    plan: starter  # Or free for testing
    buildCommand: pip install -r requirements.txt  # No cd needed with rootDir
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FRONTEND_URL
        fromService:
          type: web
          name: starknet-founders-bot-frontend
          property: HOST_URL  # Auto-links to frontend URL
      - key: PRODUCTION_FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11  # Specify version
    healthCheckPath: /
    disks:  # Add persistent disk for ChromaDB
      - name: chroma-data
        mountPath: /chroma_db  # Matches your app's path
        sizeGB: 1  # Adjust as needed

  # Frontend Web Service
  - type: web
    name: starknet-founders-bot-frontend
    runtime: node
    repo: https://github.com/omarespejel/roastmypitch
    rootDir: frontend
    region: frankfurt
    plan: starter
    preBuildCommand: npm install -g bun  # Install Bun before build (alternative: use Docker if needed)
    buildCommand: bun install && bun run build
    startCommand: bun start
    envVars:
      - key: GITHUB_ID
        sync: false
      - key: GITHUB_SECRET
        sync: false
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: starknet-founders-bot-frontend
          property: HOST_URL  # Auto-sets to this service's URL
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: starknet-founders-bot-backend
          property: HOST_URL  # Auto-links to backend
      - key: NODE_VERSION
        value: 20  # Specify Node version
    healthCheckPath: /  # Add for frontend
    autoDeploy: true  # Enable auto-deploys on Git push

# Database - ChromaDB files persist with disk storage above 