services:
  # Backend API Service
  - type: web
    name: starknet-founders-bot-backend
    runtime: python3
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: FRONTEND_URL
        value: http://localhost:3000  # Will be updated after frontend deployment
      - key: PRODUCTION_FRONTEND_URL
        sync: false  # Set to frontend URL after deployment
    healthCheckPath: /
    
  # Frontend Web Service  
  - type: web
    name: starknet-founders-bot-frontend
    runtime: node
    buildCommand: cd frontend && bun install && bun run build
    startCommand: cd frontend && bun start
    envVars:
      - key: GITHUB_ID
        sync: false  # Set manually in Render dashboard
      - key: GITHUB_SECRET
        sync: false  # Set manually in Render dashboard
      - key: NEXTAUTH_URL
        sync: false  # Set to this service's URL after deployment
      - key: NEXTAUTH_SECRET
        sync: false  # Generate random 32-character string
      - key: NEXT_PUBLIC_API_URL
        sync: false  # Set to backend service URL after deployment
    healthCheckPath: /

# Database - ChromaDB files are local, no external database needed

# Optional: Static file hosting for assets (if needed later)
# - type: static
#   name: starknet-founders-bot-assets
#   buildCommand: echo "Static assets"
#   publishPath: frontend/public 